name:demo
on:push
jobs:
 name:code
 run:ubuntu _latest
 steps:
 name:checkout code
 uses:actions@checkout@v2
 name:demo
 uses:github/demo.yml
 env:
 default branch:main
 githut_token:$((secrets.github_token))
 
