name:demo
on:push
jobs:
    name:code
    run:ubuntu _latest
 steps:
   name:check out code
   uses:actions/checkout@v2
   name:run
   uses:github/demo.yml@v2
 env:
 default branch:main
 githut_token:$((secrets.github_token))
 
